spring:
  servlet:
    multipart:
      enabled: true # enable support of multipart uploads. [true]
      file-size-threshold: 30MB # threshold after which files are written to disk. [0B]
      max-file-size: 30MB # max file size. [1MB]
      max-request-size: 30MB # max request size. [10MB]
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:

      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_discovery?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    hikari:
      minimum-idle: 10
      idle-timeout: 10000
      maximum-pool-size: 30

